# ==========================================================
# XRAV CAPES - build properties
# Ajuste apenas estas linhas para compilar em outra 1.21.x
# ==========================================================
org.gradle.jvmargs=-Xmx2G

# Minecraft / mapeamentos / loader / fabric api
# Fixado para 1.21.11 (última versão com suporte a Yarn Mappings).
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
loader_version=0.18.1
fabric_version=0.141.6+1.21.11

# Mod
mod_version=1.0.0
maven_group=com.ravenastar.xravcapes
archives_base_name=xravcapes
